### ISSUE TITLE
Squares instead of wpt name

### ISSUE THREAD

**Issue by sikmir** [dayanuyim/GisEditor#17]
### Steps to reproduce
1. Add wpt
2. Edit wpt Name
### Actual behaviour
Letters displayed as squares on map (I guess it's some font problem):
![wpt-name](https://user-images.githubusercontent.com/688044/48959897-cd585680-ef79-11e8-8511-33ce50e79745.png)
### Expected behaviour
The name should be properly displayed.
### Configuration
GisEditor: 0.26
OS: Archlinux (`ttf-arphic-ukai` font installed)
Locale: en_US.UTF-8

**Comment by dayanuyim** [comment]
GisEditor would try to set the proper font, but not do it well.
Wuld you mind to check the setting `img_font` in `~/.config/giseditor/giseditor.user.conf`, if it is set to the correct font?

Or you can try [Arial Unicode](https://www.wfonts.com/font/arial-unicode-ms), I usually used it.

**Comment by sikmir** [comment]
> Wuld you mind to check the setting img_font in ~/.config/giseditor/giseditor.user.conf, if it is set to the correct font?

Here is my default setting:
```bash
$ crudini --get ~/.config/giseditor/giseditor.user.conf settings img_font
/usr/share/fonts/TTF/DroidSansEthiopic-Bold.ttf
$ pacman -Qo /usr/share/fonts/TTF/DroidSansEthiopic-Bold.ttf
/usr/share/fonts/TTF/DroidSansEthiopic-Bold.ttf is owned by ttf-droid 20121017-6
```

It looks like the problem with `DroidSansEthiopic-Bold` font (don't know why it has been chosen by default). I've changed to `DroidSerif-Bold` and it's OK now.
```bash
$ crudini --set ~/.config/giseditor/giseditor.user.conf settings img_font /usr/share/fonts/TTF/DroidSerif-Bold.ttf
```

**Comment by dayanuyim** [comment]
Thanks for your testing!

No idea why `img_font` is different between `giseditor.user.conf`  (DroidSansEthiopic-Bold.ttf) and the log (NotoSansBengaliUI-Medium.ttf). 

I think `DroidSansEthiopic-Bold.ttf` is just selected _by random_, because no preferred fonts are found.

The font problem tumbles me a lot. To mitigate, maybe I should:
 - warn users if no preferred fonts installed.
 - A font picker allows users to change the font after the app started up.
